'use client';

import { Suspense, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { AlertCircle, ArrowLeft, CheckCircle2, Clock, Download, Loader2 } from 'lucide-react';
import { api, DetailedMom, MomResult } from '@/lib/api';
import { StatusBadge } from '@/components/ui/StatusBadge';

function MomViewContent() {
  const searchParams = useSearchParams();
  const id = searchParams.get('id') || '';
  const [mom, setMom] = useState<DetailedMom | null>(null);
  const [result, setResult] = useState<MomResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchMom = useCallback(async () => {
    if (!id) {
      setError('Missing MOM id');
      setLoading(false);
      return true;
    }

    try {
      const data = await api.getMom(id);
      setMom(data);

      if (data.status === 'COMPLETED') {
        const momResult = await api.getMomResult(id);
        setResult(momResult);
        setLoading(false);
        return true;
      }

      if (data.status === 'FAILED') {
        setLoading(false);
        return true;
      }

      setLoading(false);
      return false;
    } catch (err: any) {
      setError(err.message || 'Failed to load MOM');
      setLoading(false);
      return true;
    }
  }, [id]);

  useEffect(() => {
    let timer: NodeJS.Timeout;

    async function poll() {
      const done = await fetchMom();
      if (!done) timer = setTimeout(poll, 3000);
    }

    poll();
    return () => clearTimeout(timer);
  }, [fetchMom]);

  if (loading && !mom) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] space-y-4">
        <Loader2 className="animate-spin text-accent" size={40} />
        <p className="text-text-secondary">Loading MOM...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-xl mx-auto mt-20 card p-8 text-center space-y-6">
        <AlertCircle size={32} className="mx-auto text-danger" />
        <h3 className="text-xl font-semibold text-text-primary">Failed to load</h3>
        <p className="text-text-secondary">{error}</p>
        <Link href="/mom" className="inline-block px-6 py-2 bg-accent text-accent-foreground font-semibold rounded-md">
          Back to MOMs
        </Link>
      </div>
    );
  }

  const inProgress = mom?.status === 'PROCESSING' || mom?.status === 'CREATED';
  const handleDownloadReport = async () => {
    if (!result || !id) return;

    setDownloading(true);
    try {
      const { download_url } = await api.getMomReportUrl(id);
      window.location.href = download_url;
    } catch (err: any) {
      setError(err.message || 'Failed to download MOM report');
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-8">
      <div className="flex items-center justify-between">
        <Link href="/mom" className="flex items-center gap-2 text-text-secondary hover:text-text-primary transition-colors text-xs font-normal">
          <ArrowLeft size={16} />
          Back to MOMs
        </Link>
        <StatusBadge status={mom?.status || 'CREATED'} variant="pill" />
      </div>

      <header className="space-y-2">
        <p className="text-[11px] font-semibold tracking-[0.12em] text-accent uppercase">MOM Report</p>
        <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
          <div>
            <p className="text-sm font-semibold text-accent">{mom?.project_title || 'General'}</p>
            <h1 className="text-3xl font-bold text-text-primary tracking-tight">{result?.title || mom?.title || 'Untitled meeting'}</h1>
            <p className="text-xs text-text-muted mt-2">Generated by Minfy AI MOM Analyzer</p>
          </div>
          {result && (
            <button
              onClick={handleDownloadReport}
              disabled={downloading}
              className="inline-flex items-center justify-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-sm font-semibold text-white transition-opacity hover:opacity-90"
            >
              {downloading ? <Loader2 size={16} className="animate-spin" /> : <Download size={16} />}
              {downloading ? 'Preparing PDF' : 'Download PDF'}
            </button>
          )}
        </div>
        {result?.date && <p className="text-sm text-text-muted">{result.date}</p>}
      </header>

      {inProgress && (
        <div className="card p-8 text-center space-y-4">
          <Clock size={36} className="mx-auto text-accent" />
          <div>
            <h2 className="text-lg font-semibold text-text-primary">Analysis in progress</h2>
            <p className="text-sm text-text-secondary mt-1">This page refreshes automatically every few seconds.</p>
          </div>
        </div>
      )}

      {mom?.status === 'FAILED' && (
        <div className="card p-6 border-danger/30 bg-danger/5">
          <div className="flex gap-3">
            <AlertCircle className="text-danger shrink-0" size={22} />
            <div>
              <h2 className="text-sm font-semibold text-danger">MOM analysis failed</h2>
              <p className="text-sm text-text-secondary mt-1">{mom.error?.message || 'Please try uploading the transcript again.'}</p>
            </div>
          </div>
        </div>
      )}

      {result && (
        <div className="space-y-6">
          <section className="card p-6 space-y-4">
            <div className="flex items-center gap-2">
              <CheckCircle2 size={18} className="text-success" />
              <h2 className="text-lg font-semibold text-text-primary">Overall Summary</h2>
            </div>
            <p className="text-sm leading-7 text-text-secondary whitespace-pre-line">{result.overall_summary}</p>
          </section>

          <section className="card p-6 space-y-4">
            <h2 className="text-lg font-semibold text-text-primary">Attendees</h2>
            <div className="flex flex-wrap gap-2">
              {safeAttendees(result.attendees).map((attendee) => (
                <span key={`${attendee.name}-${attendee.role || ''}`} className="px-2.5 py-1 rounded-full bg-accent/10 text-accent text-xs font-semibold">
                  {attendee.role ? `${attendee.name} · ${attendee.role}` : attendee.name}
                </span>
              ))}
            </div>
          </section>

          <section className="card p-6 space-y-5">
            <h2 className="text-lg font-semibold text-text-primary">Discussion Points</h2>
            {result.discussion_points.map((point, index) => (
              <div key={`${point.topic}-${index}`} className="rounded-lg border border-border p-4 bg-surface">
                <h3 className="text-sm font-semibold text-text-primary">{point.topic || 'Discussion point'}</h3>
                <p className="text-sm text-text-secondary leading-6 mt-2">{point.summary}</p>
                {point.decisions.length > 0 && (
                  <div className="mt-4">
                    <p className="text-xs font-semibold text-text-muted mb-2">Decisions</p>
                    <ul className="space-y-1 text-sm text-text-secondary">
                      {point.decisions.map((decision: any, decisionIndex) => (
                        <li key={`${decision.decision || decision}-${decisionIndex}`}>- {typeof decision === 'string' ? decision : decision.decision}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {point.action_items.length > 0 && (
                  <div className="mt-4 overflow-x-auto">
                    <p className="text-xs font-semibold text-text-muted mb-2">Action Items</p>
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="text-text-muted">
                          <th className="text-left py-2">Owner</th>
                          <th className="text-left py-2">Task</th>
                          <th className="text-left py-2">Due</th>
                        </tr>
                      </thead>
                      <tbody>
                        {point.action_items.map((action, actionIndex) => (
                          <tr key={`${action.task}-${actionIndex}`} className="border-t border-border">
                            <td className="py-2 text-text-primary">{action.owner}</td>
                            <td className="py-2 text-text-secondary">{action.task}</td>
                            <td className="py-2 text-text-secondary">{action.due_date}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            ))}
          </section>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <ListSection title="Agenda Items" items={result.agenda_items} />
            <ListSection title="Risks" items={result.risks.map((risk: any) => typeof risk === 'string' ? risk : risk.description)} />
          </div>
          <ListSection title="Next Steps" items={result.next_steps} numbered />
        </div>
      )}
    </div>
  );
}

function safeList(items: string[]) {
  const cleaned = items
    .filter(Boolean)
    .map((item) => item.replace(/\s*[-–—]\s*(role\s+)?not specified\s*$/i, '').trim())
    .filter(Boolean);
  return cleaned.length ? cleaned : ['Not specified'];
}

function safeAttendees(items: any[]) {
  const cleaned = (items || []).map((item) => {
    if (typeof item === 'string') {
      return { name: item.replace(/\s*[-–—]\s*(role\s+)?not specified\s*$/i, '').trim() };
    }
    return {
      name: item?.name || 'Not specified',
      role: item?.role && !/not specified/i.test(item.role) ? item.role : '',
      organisation: item?.organisation,
    };
  }).filter((item) => item.name);
  return cleaned.length ? cleaned : [{ name: 'Not specified' }];
}

function ListSection({ title, items, numbered = false }: { title: string; items: string[]; numbered?: boolean }) {
  const safeItems = safeList(items);
  return (
    <section className="card p-6 space-y-3">
      <h2 className="text-lg font-semibold text-text-primary">{title}</h2>
      {numbered ? (
        <ol className="space-y-2 text-sm text-text-secondary list-decimal list-inside">
          {safeItems.map((item) => <li key={item}>{item}</li>)}
        </ol>
      ) : (
        <ul className="space-y-2 text-sm text-text-secondary">
          {safeItems.map((item) => <li key={item}>- {item}</li>)}
        </ul>
      )}
    </section>
  );
}

export default function MomViewPage() {
  return (
    <Suspense fallback={<div className="min-h-[60vh] flex items-center justify-center"><Loader2 className="animate-spin text-accent" /></div>}>
      <MomViewContent />
    </Suspense>
  );
}
