import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from 'pdf-lib';
import { MomResult } from '../../schema/mom.js';

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 38;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const BODY_SIZE = 9.2;
const LINE_HEIGHT = 13;

type PdfColor = ReturnType<typeof rgb>;
type CellStyle = { color?: PdfColor; bold?: boolean };

type PdfContext = {
  pdf: PDFDocument;
  page: PDFPage;
  regular: PDFFont;
  bold: PDFFont;
  y: number;
};

const c = {
  ink: rgb(0.10, 0.16, 0.24),
  muted: rgb(0.42, 0.48, 0.56),
  border: rgb(0.86, 0.90, 0.94),
  blue: rgb(0.12, 0.36, 0.62),
  blueSoft: rgb(0.91, 0.96, 1),
  bluePale: rgb(0.96, 0.98, 1),
  green: rgb(0.12, 0.56, 0.36),
  greenSoft: rgb(0.86, 0.97, 0.91),
  red: rgb(0.72, 0.18, 0.20),
  redSoft: rgb(1, 0.91, 0.91),
  amber: rgb(0.72, 0.43, 0.06),
  amberSoft: rgb(1, 0.96, 0.84),
  purple: rgb(0.42, 0.28, 0.64),
  purpleSoft: rgb(0.94, 0.90, 0.99),
  gray: rgb(0.42, 0.48, 0.56),
  graySoft: rgb(0.96, 0.97, 0.98),
  white: rgb(1, 1, 1),
  row: rgb(0.98, 0.99, 1),
};

export async function generateMomPdfReport(
  result: MomResult,
  options: { projectTitle?: string } = {},
): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const ctx: PdfContext = {
    pdf,
    page: pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
    regular,
    bold,
    y: PAGE_HEIGHT - MARGIN,
  };

  const projectTitle = options.projectTitle || 'General';
  drawTitle(ctx, result, projectTitle);
  drawMeetingInfo(ctx, result, projectTitle);
  drawMetricStrip(ctx, result);

  section(ctx, 'Meeting Details', c.blueSoft, c.blue, 130);
  drawMeetingDetails(ctx, result, projectTitle);

  section(ctx, 'Executive Summary', c.blueSoft, c.blue, 70);
  boxedParagraph(ctx, result.overall_summary || 'Not specified', c.bluePale, c.blue);

  section(ctx, 'Attendees', c.blueSoft, c.blue, 90);
  drawAttendees(ctx, result.attendees);

  section(ctx, 'Agenda Items', c.blueSoft, c.blue, 70);
  drawNumberedTable(ctx, 'Agenda Item', result.agenda_items);

  section(ctx, 'Discussion Points', c.blueSoft, c.blue, 120);
  drawDiscussionPoints(ctx, result);

  section(ctx, 'Decisions Made', c.greenSoft, c.green, 92);
  drawDecisions(ctx, result);

  section(ctx, 'Action Items', c.amberSoft, c.amber, 96);
  drawActions(ctx, result);

  section(ctx, 'Risks And Blockers', c.redSoft, c.red, 96);
  drawRisks(ctx, result);

  section(ctx, 'Next Steps', c.greenSoft, c.green, 70);
  drawNumberedTable(ctx, 'Next Step', result.next_steps);

  if (hasNextMeeting(result.next_meeting)) {
    section(ctx, 'Next Meeting', c.purpleSoft, c.purple, 92);
    drawNextMeeting(ctx, result);
  }

  section(ctx, 'Review of Previous Meeting Actions', c.graySoft, c.gray, 84);
  drawPreviousActions(ctx, result);

  section(ctx, 'Distribution & Sign-Off', c.graySoft, c.gray, 130);
  drawDistribution(ctx, result);

  drawFooter(ctx);
  return Buffer.from(await pdf.save());
}

function drawTitle(ctx: PdfContext, result: MomResult, projectTitle: string) {
  text(ctx, 'Minutes of Meeting', { size: 23, isBold: true, color: c.blue, lineHeight: 27 });
  ctx.page.drawRectangle({ x: MARGIN, y: ctx.y + 4, width: CONTENT_WIDTH, height: 3, color: c.blue });
  ctx.y -= 15;
  text(ctx, `Project: ${projectTitle}`, { size: 10.5, isBold: true, color: c.blue, lineHeight: 14 });
  text(ctx, valueOr(result.title, 'Meeting Report'), { size: 12.5, color: c.muted, lineHeight: 16 });
  text(ctx, `${valueOr(result.report_type, 'Minutes of Meeting')} | ${valueOr(result.date)} | Ref: ${valueOr(result.reference_no, 'MOM-001')}`, { size: 8.5, color: c.muted });
  text(ctx, 'Generated by Minfy AI MOM Analyzer', { size: 8.5, color: c.muted });
  ctx.y -= 8;
}

function drawMeetingInfo(ctx: PdfContext, result: MomResult, projectTitle: string) {
  table(ctx, {
    columns: [
      { title: 'Field', width: 112 },
      { title: 'Details', width: CONTENT_WIDTH - 112 },
    ],
    rows: [
      ['Project', projectTitle],
      ['Date', valueOr(result.date)],
      ['Subject', valueOr(result.title, 'Meeting Report')],
      ['Report Type', valueOr(result.report_type, 'Minutes of Meeting')],
    ],
    headerColor: c.blue,
    labelColumns: [0],
  });
  ctx.y -= 4;
}

function drawMetricStrip(ctx: PdfContext, result: MomResult) {
  const metrics = [
    ['Attendees', result.attendees.length],
    ['Agenda', result.agenda_items.filter(isUsefulText).length],
    ['Topics', result.discussion_points.length],
    ['Decisions', collectDecisions(result).length],
    ['Actions', collectActions(result).length],
    ['Risks', result.risks.length],
  ];

  ensure(ctx, 64);
  const gap = 6;
  const width = (CONTENT_WIDTH - gap * (metrics.length - 1)) / metrics.length;
  const top = ctx.y;

  metrics.forEach(([label, value], index) => {
    const x = MARGIN + index * (width + gap);
    ctx.page.drawRectangle({ x, y: top - 48, width, height: 48, color: c.bluePale, borderColor: c.border, borderWidth: 1 });
    ctx.page.drawText(String(value).padStart(2, '0'), { x: x + 8, y: top - 22, size: 14, font: ctx.bold, color: c.ink });
    ctx.page.drawText(String(label).toUpperCase(), { x: x + 8, y: top - 37, size: 6.4, font: ctx.bold, color: c.muted });
  });

  ctx.y -= 62;
}

function drawMeetingDetails(ctx: PdfContext, result: MomResult, projectTitle: string) {
  table(ctx, {
    columns: [
      { title: 'Field', width: 104 },
      { title: 'Details', width: CONTENT_WIDTH / 2 - 104 },
      { title: 'Field', width: 104 },
      { title: 'Details', width: CONTENT_WIDTH / 2 - 104 },
    ],
    rows: [
      ['Meeting Title', valueOr(result.title), 'Report Type', valueOr(result.report_type, 'Minutes of Meeting')],
      ['Date & Time', valueOr(result.date), 'Duration', valueOr(result.duration)],
      ['Platform', valueOr(result.platform), 'Reference No.', valueOr(result.reference_no, 'MOM-001')],
      ['Project', projectTitle, 'Workstream', valueOr(result.workstream)],
      ['Facilitator', valueOr(result.facilitator), 'Scribe', valueOr(result.scribe)],
      ['Distribution', valueOr(result.distribution, 'All Attendees'), 'Issued Date', valueOr(result.issued_date, result.date || 'Not specified')],
    ],
    headerColor: c.blue,
    labelColumns: [0, 2],
  });
}

function drawAttendees(ctx: PdfContext, attendees: MomResult['attendees']) {
  const roleMissing = attendees.some(attendee => !isUsefulText(attendee.role));
  if (roleMissing) {
    note(ctx, 'Some attendee roles were not specified in the transcript; those role cells are shown as "-".');
  }

  table(ctx, {
    columns: [
      { title: 'Name', width: CONTENT_WIDTH * 0.31 },
      { title: 'Role', width: CONTENT_WIDTH * 0.34 },
      { title: 'Organisation', width: CONTENT_WIDTH * 0.25 },
      { title: 'Attended', width: CONTENT_WIDTH * 0.10 },
    ],
    rows: (attendees.length ? attendees : [{ name: 'Not specified' }]).map(attendee => [
      valueOr(attendee.name),
      isUsefulText(attendee.role) ? attendee.role! : '-',
      isUsefulText(attendee.organisation) ? attendee.organisation! : '-',
      'Yes',
    ]),
    headerColor: c.blue,
    stripe: true,
  });
}

function drawNumberedTable(ctx: PdfContext, title: string, items: string[]) {
  const rows = (items.filter(isUsefulText).length ? items.filter(isUsefulText) : ['Not specified']).map((item, index) => [String(index + 1), item]);
  table(ctx, {
    columns: [
      { title: '#', width: 42 },
      { title, width: CONTENT_WIDTH - 42 },
    ],
    rows,
    headerColor: c.blue,
    stripe: true,
  });
}

function drawDiscussionPoints(ctx: PdfContext, result: MomResult) {
  const points = result.discussion_points.length ? result.discussion_points : [{ topic: 'Not specified', summary: 'Not specified', decisions: [], action_items: [] }];
  points.slice(0, 12).forEach((point, index) => {
    const summaryLines = wrap(valueOr(point.summary), ctx.regular, BODY_SIZE, CONTENT_WIDTH - 18);
    const height = 34 + summaryLines.length * LINE_HEIGHT + 16;
    ensure(ctx, height + 10);
    const top = ctx.y;
    ctx.page.drawRectangle({ x: MARGIN, y: top - 28, width: CONTENT_WIDTH, height: 28, color: c.bluePale, borderColor: c.border, borderWidth: 1 });
    ctx.page.drawRectangle({ x: MARGIN, y: top - 28, width: 4, height: 28, color: c.blue });
    ctx.page.drawText(`#${index + 1}`, { x: MARGIN + 12, y: top - 17, size: 8.5, font: ctx.bold, color: c.blue });
    ctx.page.drawText(valueOr(point.topic, 'Discussion Point'), { x: MARGIN + 50, y: top - 17, size: 9.5, font: ctx.bold, color: c.ink });
    if (isUsefulText(point.raised_by)) {
      ctx.page.drawText(`Raised by: ${safe(point.raised_by!)}`, { x: MARGIN + CONTENT_WIDTH - 180, y: top - 17, size: 7.5, font: ctx.regular, color: c.muted });
    }
    ctx.y -= 36;
    boxedParagraph(ctx, valueOr(point.summary), c.white, c.border);
  });
}

function drawDecisions(ctx: PdfContext, result: MomResult) {
  const rows = collectDecisions(result).map((decision, index) => [
    `DEC-${String(index + 1).padStart(3, '0')}`,
    decision.decision,
    valueOr(decision.rationale, '-'),
    valueOr(decision.decided_by, '-'),
  ]);
  table(ctx, {
    columns: [
      { title: 'Ref', width: 58 },
      { title: 'Decision', width: CONTENT_WIDTH * 0.36 },
      { title: 'Rationale', width: CONTENT_WIDTH * 0.31 },
      { title: 'Decided By', width: CONTENT_WIDTH - 58 - CONTENT_WIDTH * 0.36 - CONTENT_WIDTH * 0.31 },
    ],
    rows: rows.length ? rows : [['-', 'No decisions recorded.', '-', '-']],
    headerColor: c.green,
    stripe: true,
    cellStyle: (_value, column) => column === 0 ? { color: c.blue, bold: true } : {},
  });
}

function drawActions(ctx: PdfContext, result: MomResult) {
  const rows = collectActions(result).map((action, index) => [
    `ACT-${String(index + 1).padStart(3, '0')}`,
    action.task,
    valueOr(action.owner, 'Unassigned'),
    valueOr(action.due_date, 'TBD'),
    action.priority || 'Medium',
  ]);
  table(ctx, {
    columns: [
      { title: 'Ref', width: 58 },
      { title: 'Action Description', width: CONTENT_WIDTH * 0.37 },
      { title: 'Owner', width: CONTENT_WIDTH * 0.19 },
      { title: 'Due Date', width: CONTENT_WIDTH * 0.16 },
      { title: 'Priority', width: CONTENT_WIDTH - 58 - CONTENT_WIDTH * 0.37 - CONTENT_WIDTH * 0.19 - CONTENT_WIDTH * 0.16 },
    ],
    rows: rows.length ? rows : [['-', 'No actions recorded.', '-', '-', '-']],
    headerColor: c.amber,
    stripe: true,
    cellText: (value, column) => column === 4 ? priorityText(value) : value,
    cellStyle: (value, column) => {
      if (column === 0) return { color: c.blue, bold: true };
      if (column === 4) return priorityStyle(value);
      return {};
    },
  });
}

function drawRisks(ctx: PdfContext, result: MomResult) {
  const rows = result.risks.map((risk, index) => [
    `RSK-${String(index + 1).padStart(3, '0')}`,
    risk.description,
    risk.likelihood || 'M',
    risk.impact || 'M',
    valueOr(risk.owner, '-'),
    valueOr(risk.mitigation, 'To be determined'),
  ]);
  table(ctx, {
    columns: [
      { title: 'Ref', width: 54 },
      { title: 'Description', width: CONTENT_WIDTH * 0.29 },
      { title: 'Like.', width: 42 },
      { title: 'Impact', width: 46 },
      { title: 'Owner', width: CONTENT_WIDTH * 0.16 },
      { title: 'Mitigation', width: CONTENT_WIDTH - 54 - CONTENT_WIDTH * 0.29 - 42 - 46 - CONTENT_WIDTH * 0.16 },
    ],
    rows: rows.length ? rows : [['-', 'No risks recorded.', '-', '-', '-', '-']],
    headerColor: c.red,
    stripe: true,
    cellStyle: (value, column) => {
      if (column === 0) return { color: c.blue, bold: true };
      if (column === 2 || column === 3) return severityStyle(value);
      return {};
    },
  });
}

function drawNextMeeting(ctx: PdfContext, result: MomResult) {
  const meeting = result.next_meeting;
  labelValueTable(ctx, [
    ['Date & Time', valueOr(meeting?.date, 'To be confirmed')],
    ['Purpose', valueOr(meeting?.purpose)],
    ['Proposed Agenda', valueOr(meeting?.proposed_agenda)],
    ['Prep Required', valueOr(meeting?.prep_required)],
  ]);
}

function drawPreviousActions(ctx: PdfContext, result: MomResult) {
  const rows = (result.previous_actions || []).map(action => [
    valueOr(action.ref, '-'),
    action.action,
    valueOr(action.owner, '-'),
    valueOr(action.status, '-'),
  ]);
  table(ctx, {
    columns: [
      { title: 'Ref', width: 58 },
      { title: 'Action', width: CONTENT_WIDTH * 0.47 },
      { title: 'Owner', width: CONTENT_WIDTH * 0.24 },
      { title: 'Status', width: CONTENT_WIDTH - 58 - CONTENT_WIDTH * 0.47 - CONTENT_WIDTH * 0.24 },
    ],
    rows: rows.length ? rows : [['-', 'No previous meeting actions - this is the first recorded meeting for this workstream.', '-', '-']],
    headerColor: c.gray,
    stripe: true,
  });
}

function drawDistribution(ctx: PdfContext, result: MomResult) {
  const attendees = result.attendees.map(attendee => attendee.name).filter(isUsefulText).join(', ') || 'All Attendees';
  labelValueTable(ctx, [
    ['Prepared By', `${valueOr(result.scribe)} | ${valueOr(result.issued_date, result.date || 'Not specified')}`],
    ['Reviewed By', 'Pending'],
    ['Distributed To', attendees],
    ['Review Deadline', 'Please raise any objections within 48 hours. Silence implies acceptance.'],
    ['Storage Location', 'SharePoint / Confluence'],
  ]);
  ensure(ctx, 54);
  ctx.page.drawRectangle({ x: MARGIN, y: ctx.y - 44, width: CONTENT_WIDTH, height: 44, color: c.graySoft, borderColor: c.border, borderWidth: 1 });
  const end = '- End of Minutes of Meeting -';
  ctx.page.drawText(end, { x: PAGE_WIDTH / 2 - ctx.bold.widthOfTextAtSize(end, 8.5) / 2, y: ctx.y - 18, size: 8.5, font: ctx.bold, color: c.ink });
  const noteText = 'This document is confidential and intended solely for the addressees listed above.';
  ctx.page.drawText(noteText, { x: PAGE_WIDTH / 2 - ctx.regular.widthOfTextAtSize(noteText, 7) / 2, y: ctx.y - 32, size: 7, font: ctx.regular, color: c.muted });
  ctx.y -= 54;
}

function labelValueTable(ctx: PdfContext, rows: string[][]) {
  table(ctx, {
    columns: [
      { title: 'Field', width: CONTENT_WIDTH * 0.25 },
      { title: 'Details', width: CONTENT_WIDTH * 0.75 },
    ],
    rows,
    headerColor: c.gray,
    labelColumns: [0],
    stripe: true,
  });
}

function section(ctx: PdfContext, title: string, fill: PdfColor, accent: PdfColor, minFollowingSpace = 72) {
  const titleLines = wrap(safe(title), ctx.bold, 11.5, CONTENT_WIDTH - 24);
  const height = Math.max(28, titleLines.length * 13 + 14);
  ensure(ctx, height + minFollowingSpace);
  ctx.y -= 10;
  ctx.page.drawRectangle({ x: MARGIN, y: ctx.y - height + 3, width: CONTENT_WIDTH, height, color: fill });
  ctx.page.drawRectangle({ x: MARGIN, y: ctx.y - height + 3, width: 4, height, color: accent });
  titleLines.forEach((line, index) => {
    ctx.page.drawText(line, { x: MARGIN + 12, y: ctx.y - 15 - index * 13, size: 11.5, font: ctx.bold, color: accent });
  });
  ctx.y -= height + 13;
}

function boxedParagraph(ctx: PdfContext, value: string, fill: PdfColor, accent: PdfColor) {
  const lines = wrap(valueOr(value), ctx.regular, BODY_SIZE, CONTENT_WIDTH - 24);
  const height = Math.max(42, lines.length * LINE_HEIGHT + 22);
  ensure(ctx, height + 8);
  const top = ctx.y;
  ctx.page.drawRectangle({ x: MARGIN, y: top - height, width: CONTENT_WIDTH, height, color: fill, borderColor: accent, borderWidth: 0.7 });
  lines.forEach((line, index) => {
    ctx.page.drawText(line, { x: MARGIN + 12, y: top - 17 - index * LINE_HEIGHT, size: BODY_SIZE, font: ctx.regular, color: c.ink });
  });
  ctx.y -= height + 9;
}

function note(ctx: PdfContext, value: string) {
  const lines = wrap(value, ctx.regular, 8, CONTENT_WIDTH - 22);
  const height = Math.max(26, lines.length * 11 + 13);
  ensure(ctx, height + 8);
  const top = ctx.y;
  ctx.page.drawRectangle({ x: MARGIN, y: top - height, width: CONTENT_WIDTH, height, color: c.bluePale, borderColor: c.border, borderWidth: 1 });
  lines.forEach((line, index) => {
    ctx.page.drawText(line, { x: MARGIN + 11, y: top - 15 - index * 11, size: 8, font: ctx.regular, color: c.muted });
  });
  ctx.y -= height + 7;
}

function table(ctx: PdfContext, options: {
  columns: Array<{ title: string; width: number }>;
  rows: string[][];
  headerColor: PdfColor;
  stripe?: boolean;
  labelColumns?: number[];
  cellText?: (value: string, column: number, row: number) => string;
  cellStyle?: (value: string, column: number, row: number) => CellStyle;
}) {
  const headerHeight = 23;
  const drawHeader = () => {
    let x = MARGIN;
    options.columns.forEach(column => {
      ctx.page.drawRectangle({ x, y: ctx.y - headerHeight, width: column.width, height: headerHeight, color: options.headerColor, borderColor: options.headerColor, borderWidth: 1 });
      ctx.page.drawText(column.title, { x: x + 7, y: ctx.y - 15, size: 8.3, font: ctx.bold, color: c.white });
      x += column.width;
    });
    ctx.y -= headerHeight;
  };

  ensure(ctx, 64);
  drawHeader();

  options.rows.forEach((row, rowIndex) => {
    const wrapped = row.map((cell, index) => wrap(valueOr(options.cellText?.(cell, index, rowIndex) || cell), ctx.regular, 8.4, options.columns[index].width - 14));
    const height = Math.max(27, Math.max(...wrapped.map(lines => lines.length)) * 11 + 14);
    if (ctx.y - height < MARGIN + 28) {
      ctx.page = ctx.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      ctx.y = PAGE_HEIGHT - MARGIN;
      drawHeader();
    }

    let cellX = MARGIN;
    wrapped.forEach((lines, index) => {
      const isLabel = options.labelColumns?.includes(index);
      const fill = isLabel ? c.graySoft : options.stripe && rowIndex % 2 === 1 ? c.row : c.white;
      ctx.page.drawRectangle({ x: cellX, y: ctx.y - height, width: options.columns[index].width, height, color: fill, borderColor: c.border, borderWidth: 1 });
      const style = options.cellStyle?.(row[index] || '', index, rowIndex) || {};
      lines.forEach((line, lineIndex) => {
        ctx.page.drawText(line, { x: cellX + 7, y: ctx.y - 15 - lineIndex * 11, size: 8.4, font: style.bold || isLabel || index === 0 ? ctx.bold : ctx.regular, color: style.color || c.ink });
      });
      cellX += options.columns[index].width;
    });

    ctx.y -= height;
  });

  ctx.y -= 8;
}

function text(ctx: PdfContext, value: string, options: { size?: number; isBold?: boolean; color?: PdfColor; indent?: number; lineHeight?: number } = {}) {
  const size = options.size || BODY_SIZE;
  const font = options.isBold ? ctx.bold : ctx.regular;
  const indent = options.indent || 0;
  const lines = wrap(valueOr(value), font, size, CONTENT_WIDTH - indent);
  lines.forEach(line => {
    ensure(ctx, (options.lineHeight || LINE_HEIGHT) + 2);
    ctx.page.drawText(line, { x: MARGIN + indent, y: ctx.y, size, font, color: options.color || c.ink });
    ctx.y -= options.lineHeight || LINE_HEIGHT;
  });
}

function drawFooter(ctx: PdfContext) {
  ctx.pdf.getPages().forEach((page, index) => {
    page.drawRectangle({ x: MARGIN, y: 32, width: CONTENT_WIDTH, height: 1, color: c.border });
    page.drawText('Minfy AI MOM Analyzer', { x: MARGIN, y: 18, size: 7.5, font: ctx.regular, color: c.muted });
    page.drawText(`Page ${index + 1}`, { x: PAGE_WIDTH - MARGIN - 38, y: 18, size: 7.5, font: ctx.regular, color: c.muted });
  });
}

function ensure(ctx: PdfContext, height: number) {
  if (ctx.y - height > MARGIN + 18) return;
  ctx.page = ctx.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  ctx.y = PAGE_HEIGHT - MARGIN;
}

function collectDecisions(result: MomResult) {
  return result.discussion_points.flatMap(point => point.decisions || []).filter(decision => isUsefulText(decision.decision));
}

function collectActions(result: MomResult) {
  return result.discussion_points.flatMap(point => point.action_items || []).filter(action => isUsefulText(action.task));
}

function hasNextMeeting(value: MomResult['next_meeting']): boolean {
  if (!value) return false;
  return [value.date, value.purpose, value.proposed_agenda, value.prep_required].some(isUsefulText);
}

function priorityText(value: string): string {
  if (value === 'High') return `* ${value}`;
  if (value === 'Low') return `o ${value}`;
  if (value === '-') return value;
  return `- ${value || 'Medium'}`;
}

function priorityStyle(value: string): CellStyle {
  if (value === 'High') return { color: c.red, bold: true };
  if (value === 'Low') return { color: c.green };
  return { color: c.amber };
}

function severityStyle(value: string): CellStyle {
  if (value === 'H') return { color: c.red, bold: true };
  if (value === 'L') return { color: c.green };
  return { color: c.amber };
}

function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const words = safe(text).split(/\s+/).filter(Boolean).flatMap(word => splitWordToFit(word, font, size, width));
  if (!words.length) return ['Not specified'];
  const lines: string[] = [];
  let line = '';
  words.forEach(word => {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= width) {
      line = candidate;
    } else {
      if (line) lines.push(line);
      line = word;
    }
  });
  if (line) lines.push(line);
  return lines;
}

function splitWordToFit(word: string, font: PDFFont, size: number, width: number): string[] {
  if (font.widthOfTextAtSize(word, size) <= width) return [word];
  const parts: string[] = [];
  let part = '';
  for (const char of word) {
    const candidate = part + char;
    if (part && font.widthOfTextAtSize(`${candidate}-`, size) > width) {
      parts.push(`${part}-`);
      part = char;
    } else {
      part = candidate;
    }
  }
  if (part) parts.push(part);
  return parts;
}

function isUsefulText(value: string | undefined | null): boolean {
  const textValue = safe(value || '').toLowerCase();
  return !!textValue && textValue !== 'not specified' && textValue !== 'n/a';
}

function valueOr(value: string | undefined | null, fallback = 'Not specified'): string {
  return isUsefulText(value) ? safe(value!) : fallback;
}

function safe(text: string): string {
  return String(text || '')
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, ' ')
    .replace(/[ \t]+/g, ' ')
    .trim();
}
