import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from 'pdf-lib';
import { MomResult } from '../../schema/mom.js';

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 38;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const BODY_SIZE = 9.5;
const LINE_HEIGHT = 13.5;

type PdfColor = ReturnType<typeof rgb>;

type PdfContext = {
  pdf: PDFDocument;
  page: PDFPage;
  regular: PDFFont;
  bold: PDFFont;
  y: number;
};

const c = {
  ink: rgb(0.10, 0.16, 0.24),
  muted: rgb(0.42, 0.48, 0.56),
  border: rgb(0.86, 0.90, 0.94),
  blue: rgb(0.12, 0.36, 0.62),
  blueSoft: rgb(0.91, 0.96, 1),
  bluePale: rgb(0.96, 0.98, 1),
  green: rgb(0.12, 0.56, 0.36),
  greenSoft: rgb(0.86, 0.97, 0.91),
  red: rgb(0.72, 0.18, 0.20),
  redSoft: rgb(1, 0.91, 0.91),
  amber: rgb(0.72, 0.43, 0.06),
  amberSoft: rgb(1, 0.96, 0.84),
  purple: rgb(0.42, 0.28, 0.64),
  purpleSoft: rgb(0.94, 0.90, 0.99),
  white: rgb(1, 1, 1),
  row: rgb(0.98, 0.99, 1),
};

export async function generateMomPdfReport(result: MomResult): Promise<Buffer> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const ctx: PdfContext = {
    pdf,
    page: pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]),
    regular,
    bold,
    y: PAGE_HEIGHT - MARGIN,
  };

  drawTitle(ctx, result);
  drawMeetingInfo(ctx, result);
  drawMetricStrip(ctx, result);
  drawAttendees(ctx, result.attendees);

  section(ctx, 'Executive Summary', c.blueSoft, c.blue);
  paragraph(ctx, result.overall_summary || 'Not specified');

  section(ctx, 'Agenda Items', c.blueSoft, c.blue);
  simpleList(ctx, result.agenda_items, 'agenda');

  result.discussion_points.slice(0, 9).forEach((point, index) => {
    section(ctx, `${index + 1}. ${point.topic || 'Discussion Point'}`, c.blueSoft, c.blue);
    paragraph(ctx, point.summary || 'Not specified');

    if (point.decisions?.length) {
      point.decisions
        .filter(isUsefulText)
        .slice(0, 5)
        .forEach(decision => callout(ctx, 'Decision', decision, c.greenSoft, c.green));
    }

    if (point.action_items?.length) {
      subheading(ctx, 'Action Items');
      drawActionTable(ctx, point.action_items.slice(0, 8));
    }
  });

  section(ctx, 'Risks And Blockers', c.redSoft, c.red);
  const risks = result.risks.filter(isUsefulText);
  if (risks.length) {
    risks.slice(0, 10).forEach(risk => callout(ctx, 'Risk', risk, c.redSoft, c.red));
  } else {
    callout(ctx, 'Risk', 'Not specified', c.redSoft, c.red);
  }

  section(ctx, 'Next Steps', c.greenSoft, c.green);
  simpleList(ctx, result.next_steps, 'next');

  drawFooter(ctx);
  return Buffer.from(await pdf.save());
}

function drawTitle(ctx: PdfContext, result: MomResult) {
  text(ctx, 'Minutes of Meeting', { size: 23, isBold: true, color: c.blue, lineHeight: 27 });
  ctx.page.drawRectangle({ x: MARGIN, y: ctx.y + 4, width: CONTENT_WIDTH, height: 3, color: c.blue });
  ctx.y -= 15;
  text(ctx, result.title || 'Meeting Report', { size: 12.5, color: c.muted, lineHeight: 16 });
  text(ctx, 'Generated by Minfy AI MOM Analyzer', { size: 8.5, color: c.muted });
  ctx.y -= 8;
}

function drawMeetingInfo(ctx: PdfContext, result: MomResult) {
  table(ctx, {
    columns: [
      { title: 'Field', width: 126 },
      { title: 'Details', width: CONTENT_WIDTH - 126 },
    ],
    rows: [
      ['Date', result.date || 'Not specified'],
      ['Subject', result.title || 'Meeting Report'],
      ['Report Type', 'Minutes of Meeting'],
    ],
    headerColor: c.blue,
  });
  ctx.y -= 6;
}

function drawMetricStrip(ctx: PdfContext, result: MomResult) {
  const metrics = [
    ['Attendees', result.attendees.length],
    ['Agenda', result.agenda_items.filter(isUsefulText).length],
    ['Topics', result.discussion_points.length],
    ['Decisions', collectDecisions(result).length],
    ['Actions', collectActions(result).length],
    ['Risks', result.risks.filter(isUsefulText).length],
  ];

  ensure(ctx, 64);
  const gap = 6;
  const width = (CONTENT_WIDTH - gap * (metrics.length - 1)) / metrics.length;
  const top = ctx.y;

  metrics.forEach(([label, value], index) => {
    const x = MARGIN + index * (width + gap);
    ctx.page.drawRectangle({
      x,
      y: top - 48,
      width,
      height: 48,
      color: c.bluePale,
      borderColor: c.border,
      borderWidth: 1,
    });
    ctx.page.drawText(String(value).padStart(2, '0'), {
      x: x + 8,
      y: top - 22,
      size: 14,
      font: ctx.bold,
      color: c.ink,
    });
    ctx.page.drawText(String(label).toUpperCase(), {
      x: x + 8,
      y: top - 37,
      size: 6.4,
      font: ctx.bold,
      color: c.muted,
    });
  });

  ctx.y -= 62;
}

function drawAttendees(ctx: PdfContext, attendees: string[]) {
  section(ctx, 'Attendees', c.blueSoft, c.blue);
  const rows = (attendees.filter(isUsefulText).length ? attendees.filter(isUsefulText) : ['Not specified'])
    .slice(0, 24)
    .map(parseAttendee);

  table(ctx, {
    columns: [
      { title: 'Name', width: CONTENT_WIDTH * 0.48 },
      { title: 'Role / Team', width: CONTENT_WIDTH * 0.52 },
    ],
    rows,
    headerColor: c.blue,
  });
}

function section(ctx: PdfContext, title: string, fill: PdfColor, accent: PdfColor) {
  const titleLines = wrap(safe(title), ctx.bold, 11.5, CONTENT_WIDTH - 24);
  const height = Math.max(28, titleLines.length * 13 + 14);
  ensure(ctx, height + 18);
  ctx.y -= 10;
  ctx.page.drawRectangle({
    x: MARGIN,
    y: ctx.y - height + 3,
    width: CONTENT_WIDTH,
    height,
    color: fill,
  });
  ctx.page.drawRectangle({
    x: MARGIN,
    y: ctx.y - height + 3,
    width: 4,
    height,
    color: accent,
  });
  titleLines.forEach((line, index) => {
    ctx.page.drawText(line, {
      x: MARGIN + 12,
      y: ctx.y - 15 - index * 13,
      size: 11.5,
      font: ctx.bold,
      color: accent,
    });
  });
  ctx.y -= height + 13;
}

function subheading(ctx: PdfContext, value: string) {
  ensure(ctx, 58);
  ctx.y -= 3;
  ctx.page.drawRectangle({
    x: MARGIN,
    y: ctx.y - 18,
    width: CONTENT_WIDTH,
    height: 22,
    color: c.purpleSoft,
  });
  ctx.page.drawRectangle({
    x: MARGIN,
    y: ctx.y - 18,
    width: 4,
    height: 22,
    color: c.purple,
  });
  ctx.page.drawText(safe(value), {
    x: MARGIN + 12,
    y: ctx.y - 12,
    size: 10,
    font: ctx.bold,
    color: c.purple,
  });
  ctx.y -= 29;
}

function callout(ctx: PdfContext, label: string, value: string, fill: PdfColor, accent: PdfColor) {
  const labelText = `${label}: `;
  const lines = wrap(safe(value || 'Not specified'), ctx.regular, BODY_SIZE, CONTENT_WIDTH - 34);
  const height = Math.max(44, lines.length * LINE_HEIGHT + 32);
  ensure(ctx, height + 8);

  const top = ctx.y;
  ctx.page.drawRectangle({
    x: MARGIN,
    y: top - height,
    width: CONTENT_WIDTH,
    height,
    color: fill,
    borderColor: c.border,
    borderWidth: 1,
  });
  ctx.page.drawRectangle({
    x: MARGIN,
    y: top - height,
    width: 4,
    height,
    color: accent,
  });
  ctx.page.drawText(labelText, {
    x: MARGIN + 14,
    y: top - 18,
    size: BODY_SIZE,
    font: ctx.bold,
    color: c.ink,
  });

  let y = top - 32;
  lines.forEach((line, index) => {
    ctx.page.drawText(line, {
      x: MARGIN + 14,
      y,
      size: BODY_SIZE,
      font: ctx.regular,
      color: c.ink,
    });
    y -= LINE_HEIGHT;
  });

  ctx.y -= height + 8;
}

function simpleList(ctx: PdfContext, items: string[], kind: 'agenda' | 'next') {
  const safeItems = items.filter(isUsefulText).length ? items.filter(isUsefulText) : ['Not specified'];
  safeItems.slice(0, 12).forEach((item, index) => {
    const prefix = kind === 'next' ? `${index + 1}.` : '-';
    text(ctx, `${prefix} ${item}`, { indent: 10, color: c.ink });
  });
  ctx.y -= 7;
}

function drawActionTable(ctx: PdfContext, actions: Array<{ owner: string; task: string; due_date: string }>) {
  const useful = actions.filter(action => isUsefulText(action.task));
  ctx.y -= 2;
  table(ctx, {
    columns: [
      { title: 'Owner', width: 112 },
      { title: 'Action', width: CONTENT_WIDTH - 210 },
      { title: 'Due Date', width: 98 },
    ],
    rows: (useful.length ? useful : [{ owner: 'Unassigned', task: 'Not specified', due_date: 'Not specified' }])
      .map(action => [
        action.owner || 'Unassigned',
        action.task || 'Not specified',
        action.due_date || 'Not specified',
      ]),
    headerColor: c.red,
    stripe: true,
  });
  ctx.y -= 4;
}

function table(ctx: PdfContext, options: {
  columns: Array<{ title: string; width: number }>;
  rows: string[][];
  headerColor: PdfColor;
  stripe?: boolean;
}) {
  ensure(ctx, 34);
  const headerHeight = 24;
  let x = MARGIN;
  options.columns.forEach(column => {
    ctx.page.drawRectangle({
      x,
      y: ctx.y - headerHeight,
      width: column.width,
      height: headerHeight,
      color: options.headerColor,
      borderColor: options.headerColor,
      borderWidth: 1,
    });
    ctx.page.drawText(column.title, {
      x: x + 8,
      y: ctx.y - 15,
      size: 8.7,
      font: ctx.bold,
      color: c.white,
    });
    x += column.width;
  });
  ctx.y -= headerHeight;

  options.rows.forEach((row, rowIndex) => {
    const wrapped = row.map((cell, index) => wrap(safe(cell), ctx.regular, 8.7, options.columns[index].width - 16));
    const height = Math.max(26, Math.max(...wrapped.map(lines => lines.length)) * 11 + 13);
    ensure(ctx, height + 3);

    let cellX = MARGIN;
    wrapped.forEach((lines, index) => {
      ctx.page.drawRectangle({
        x: cellX,
        y: ctx.y - height,
        width: options.columns[index].width,
        height,
        color: options.stripe && rowIndex % 2 === 1 ? c.row : c.white,
        borderColor: c.border,
        borderWidth: 1,
      });
      lines.forEach((line, lineIndex) => {
        ctx.page.drawText(line, {
          x: cellX + 8,
          y: ctx.y - 15 - lineIndex * 11,
          size: 8.7,
          font: index === 0 ? ctx.bold : ctx.regular,
          color: c.ink,
        });
      });
      cellX += options.columns[index].width;
    });

    ctx.y -= height;
  });

  ctx.y -= 8;
}

function paragraph(ctx: PdfContext, value: string) {
  text(ctx, value || 'Not specified', { color: c.ink, lineHeight: LINE_HEIGHT });
  ctx.y -= 5;
}

function text(ctx: PdfContext, value: string, options: {
  size?: number;
  isBold?: boolean;
  color?: PdfColor;
  indent?: number;
  lineHeight?: number;
} = {}) {
  const size = options.size || BODY_SIZE;
  const font = options.isBold ? ctx.bold : ctx.regular;
  const indent = options.indent || 0;
  const lines = wrap(safe(value), font, size, CONTENT_WIDTH - indent);

  lines.forEach(line => {
    ensure(ctx, (options.lineHeight || LINE_HEIGHT) + 2);
    ctx.page.drawText(line, {
      x: MARGIN + indent,
      y: ctx.y,
      size,
      font,
      color: options.color || c.ink,
    });
    ctx.y -= options.lineHeight || LINE_HEIGHT;
  });
}

function drawFooter(ctx: PdfContext) {
  ctx.pdf.getPages().forEach((page, index) => {
    page.drawRectangle({ x: MARGIN, y: 32, width: CONTENT_WIDTH, height: 1, color: c.border });
    page.drawText('Minfy AI MOM Analyzer', {
      x: MARGIN,
      y: 18,
      size: 7.5,
      font: ctx.regular,
      color: c.muted,
    });
    page.drawText(`Page ${index + 1}`, {
      x: PAGE_WIDTH - MARGIN - 38,
      y: 18,
      size: 7.5,
      font: ctx.regular,
      color: c.muted,
    });
  });
}

function ensure(ctx: PdfContext, height: number) {
  if (ctx.y - height > MARGIN + 12) return;
  ctx.page = ctx.pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  ctx.y = PAGE_HEIGHT - MARGIN;
}

function collectDecisions(result: MomResult): string[] {
  return result.discussion_points
    .flatMap(point => point.decisions || [])
    .filter(isUsefulText);
}

function collectActions(result: MomResult) {
  return result.discussion_points
    .flatMap(point => point.action_items || [])
    .filter(action => isUsefulText(action.task));
}

function parseAttendee(attendee: string): string[] {
  const value = safe(attendee);
  const dashMatch = value.match(/^(.+?)\s+-\s+(.+)$/);
  if (dashMatch) return [dashMatch[1], dashMatch[2]];
  const parenMatch = value.match(/^(.+?)\s+\((.+)\)$/);
  if (parenMatch) return [parenMatch[1], parenMatch[2]];
  return [value, 'Not specified'];
}

function wrap(text: string, font: PDFFont, size: number, width: number): string[] {
  const words = safe(text)
    .split(/\s+/)
    .filter(Boolean)
    .flatMap(word => splitWordToFit(word, font, size, width));
  if (!words.length) return ['Not specified'];

  const lines: string[] = [];
  let line = '';
  words.forEach(word => {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= width) {
      line = candidate;
    } else {
      if (line) lines.push(line);
      line = word;
    }
  });
  if (line) lines.push(line);
  return lines;
}

function splitWordToFit(word: string, font: PDFFont, size: number, width: number): string[] {
  if (font.widthOfTextAtSize(word, size) <= width) return [word];

  const parts: string[] = [];
  let part = '';
  for (const char of word) {
    const candidate = part + char;
    if (part && font.widthOfTextAtSize(`${candidate}-`, size) > width) {
      parts.push(`${part}-`);
      part = char;
    } else {
      part = candidate;
    }
  }
  if (part) parts.push(part);
  return parts;
}

function isUsefulText(value: string | undefined | null): boolean {
  const textValue = safe(value || '').toLowerCase();
  return !!textValue && textValue !== 'not specified' && textValue !== 'n/a';
}

function safe(text: string): string {
  return String(text || '')
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, ' ')
    .replace(/[ \t]+/g, ' ')
    .trim();
}
